name: layrz_theme_example
description: layrz_theme_example
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.10.0 <4.0.0"
  flutter: ">=3.38.0"

dependencies:
  flutter:
    sdk: flutter

  collection: any
  go_router: ^12.1.1
  shared_preferences: ^2.2.0
  url_launcher: ^6.1.12
  flutter_dotenv: ^5.1.0
  flutter_map: any
  flutter_map_animations: any

  layrz_state: any
  layrz_icons: any
  layrz_models: any
  layrz_theme:
    path: ../


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/image-test.jpg
    - assets/loading_animation.lottie
    - assets/color_palette.png
