name: "Deploy package"

on:
  pull_request:
    branches: [ main, next, development ]
    types: [ opened, synchronize, reopened ]

jobs:
  lint-dart:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Setup Flutter
        uses: flutter-actions/setup-flutter@v4
        with:
          channel: stable
          version: 3.38.8
          cache-sdk: true
          cache: true

      - name: Install dependencies
        run: flutter pub get

      - name: Run checks
        run: flutter analyze
